# cloudbuild.yaml
steps:
  # Paso 1: Construir la imagen Docker usando el Dockerfile en el directorio raíz
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA'
      - '.'

  # Paso 2: Subir la imagen a Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA'

  # Paso 3: Desplegar la imagen a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'discana-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA'
