steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/discana-api:${_SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/discana-api:${_SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "discana-api"
      - "--image=gcr.io/$PROJECT_ID/discana-api:${_SHORT_SHA}"
      - "--region=europe-west1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=${_MEMORY}"
      - "--cpu=${_CPU}"
      - "--timeout=900"
      - "--concurrency=10"
      - "--set-env-vars=API_VERSION=${_API_VERSION},MONGO_URI=${_MONGO_URI},ENCRYPTION_KEY=${_ENCRYPTION_KEY},SPOTIFY_CLIENT_ID=${_SPOTIFY_CLIENT_ID},SPOTIFY_SECRET=${_SPOTIFY_SECRET},LASTFM_API_KEY=${_LASTFM_API_KEY},LASTFM_API_SECRET=${_LASTFM_API_SECRET},DISCOGS_API_KEY=${_DISCOGS_API_KEY},DISCOGS_API_SECRET=${_DISCOGS_API_SECRET},FRONTEND_URL=${_FRONTEND_URL},API_URL=${_API_URL},GEMINI_API_KEY=${_GEMINI_API_KEY},ADMIN_TOKENS=${_ADMIN_TOKENS}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SHORT_SHA: ""
  _API_VERSION: "v2"  # Valor por defecto
  _FRONTEND_URL: ""    # Debe venir de GitHub Secrets
  _API_URL: ""         # Debe venir de GitHub Secrets
  _MONGO_URI: ""
  _ENCRYPTION_KEY: ""
  _SPOTIFY_CLIENT_ID: ""
  _SPOTIFY_SECRET: ""
  _LASTFM_API_KEY: ""
  _LASTFM_API_SECRET: ""
  _DISCOGS_API_KEY: ""
  _DISCOGS_API_SECRET: ""
  _MEMORY: "3Gi"      # Memoria aumentada para procesamiento de imágenes
  _CPU: "2"           # CPU aumentada para mejor rendimiento
  _GEMINI_API_KEY: "" # Añadido para despliegue
  _ADMIN_TOKENS: ""   # Añadido para despliegue