steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "discana-api",
        "--image",
        "gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--entry-point",
        "gunicorn -c gunicorn.conf.py app:app",
      ]

images:
  - "gcr.io/$PROJECT_ID/discana-api:$SHORT_SHA"
