
@baseUrl = http://127.0.0.1:8080/api/v2
@authHeader = Bearer YOUR

@authCode = 'AQAOHk1QVungNt7h-h6FrNAzEQyiiSDlzpPjQHTg2hBnejevel512VPLJ18Owla--ffOhTAvzDMH0ao_hElrOZ0qzVMRHhSX0WlgJklS4ErOQOnC7jomnnzWpkzZQo8GpQksrkZfYwut4X7SZrmkmFew4hunX9Ln3brjy8MDL_BHcDFCPy-HeH7v1JJ9rdXFKnjcaiX2U3DHONMISVg'

#token = 'BQAOIcKnVApi6vDFuOu7Bcm36bMf2g3vMVOgyqDfj0nYCiQF6yxUgsy_5oodGcTbeYoxV_116_VTDDVw3Dt861yuaJn8IANVr9LST-w7hlWGO25FJg-UckhpKcLROjiEBUQ4zKktrt4fZAUB8nOFpa4n20NhuaS3iNT8ha2DzP0hrMfgX-ULnftvB22pXdFANUHCHRgGgOoimUcFWAI2p472vLqlk5gH'

#access_token="gAAAAABn2byp3u6XJEfbYstA2tjbAj05LuGDDFLa0MFiA3P010a9ltq266_xDyw7ZPSsZpUp0yUDr-agykRbddSe3eXpiCL-c2DqrsYuiYc0VPuOZ_krER_fRibiF56b-hoTAPfYldO0wvVpZDlh2vb-x65KOUKa1KeTjAuHjs44y53H_R-SdHj7ndyikk4punrg4idb3vqf2Zfylxk2Koa6pcC8NdL9vsjPe84N9zt-Fxb97TM1_VlHJj26NjChVsvGAXuxr4QxGbKTWHT6AAvdVtx_K6JUhQW1IeATYvRQQu6uYyB5FruRoqOOT-6BJZu2hakc12RZidbmuwNC696kH7QpSoKbGrPV4XZBt1FHENXTNOAkm7IWo-O-qnQu4mOMi2nNhex5"


### Iniciar sesión en Spotify
GET {{baseUrl}}/s/login HTTP/1.1
#Accept: application/json 

###

### Callback de Spotify (con código de autorización)
# Asegúrate de usar el código que obtienes en la URL después de que el usuario autorice el login
GET {{baseUrl}}/s/callback?code={{authCode}} HTTP/1.1
Accept: application/json

###

### Obtener álbumes guardados de Spotify (requiere que el usuario esté autenticado)
# Usa el user_id que guardas después del login o que simulas en tu API.
GET {{baseUrl}}/s/albums?user_id=guerracanal HTTP/1.1
Accept: application/json


### Path: get spotify albums
GET {{baseUrl}}/a/spotify?user_id=guerracanal HTTP/1.1
Accept: application/json