name: Deploy API to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: discana
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          version: 'latest'

      - name: Create environment variables file
        run: |
          cat > env-vars.yaml << EOF
          API_VERSION: v2
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          DISCOGS_API_KEY: ${{ secrets.DISCOGS_API_KEY }}
          DISCOGS_API_SECRET: ${{ secrets.DISCOGS_API_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          API_URL: ${{ secrets.API_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ADMIN_TOKENS: ${{ secrets.ADMIN_TOKENS }}
          GOOGLE_CREDENTIALS_JSON: |
            ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          EOF

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/discana-api:${SHORT_SHA} .
          docker push gcr.io/$GCP_PROJECT_ID/discana-api:${SHORT_SHA}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy discana-api \
            --image gcr.io/$GCP_PROJECT_ID/discana-api:${SHORT_SHA} \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --memory 3Gi \
            --cpu 2 \
            --timeout 900 \
            --concurrency 10 \
            --env-vars-file env-vars.yaml