name: Deploy API to GCP

on:
  push:
    branches:
      - main  # Ajusta a la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: discana
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set environment variable for Mongo URI
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml .
