name: Deploy API to GCP

on:
  push:
    branches:
      - main  # Ajusta según tu rama de producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Autenticarse en GCP usando el secreto GCP_CREDENTIALS
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 3. Configurar el SDK de Google Cloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: discana

      # 4. Verificar la cuenta autenticada (opcional, para depuración)
      - name: Verify authenticated account
        run: gcloud auth list

      # 5. Establecer la variable de entorno para Mongo URI
      - name: Set environment variable for Mongo URI
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      # 6. Obtener el hash corto usando la variable predefinida GITHUB_SHA y enviar el build a Cloud Build
      - name: Submit build to Cloud Build
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "Using SHORT_SHA: $SHORT_SHA"
          gcloud builds submit --config cloudbuild.yaml --substitutions=SHORT_SHA=$SHORT_SHA,_MONGO_URI=${{ secrets.MONGO_URI }} .
