name: Deploy API to GCP

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Verify the directory structure
      run: ls -la

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1  # Asegúrate de usar la versión más reciente
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set environment variable for Mongo URI
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        PROJECT_NAME=discana
        REGION=europe-west1
        API_IMAGE_NAME=discana-api
        API_CONTAINER_NAME=gcr.io/$PROJECT_NAME/$API_IMAGE_NAME
        API_DOCKER_CONTEXT=./discana-api  

        gcloud builds submit --tag $API_CONTAINER_NAME $API_DOCKER_CONTEXT

    - name: Deploy to Cloud Run
      run: |
        API_SERVICE_NAME=discana-api
        gcloud run deploy $API_SERVICE_NAME \
          --image gcr.io/$PROJECT_NAME/$API_IMAGE_NAME \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated
